# Pair notebooks in subfolders of 'notebooks' to scripts in subfolders of 'scripts'
#formats = ".///ipynb,scripts///py:percent"
# Always pair ipynb notebooks to py:percent files
formats = ["ipynb", "scripts//py:percent"]